apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "simple-vue-app.fullname" . }}
  labels:
    {{- include "simple-vue-app.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "simple-vue-app.fullname" . }}
    weight: 100